### ISSUE TITLE
Aanmaken van users lijkt niet te werken

### ISSUE THREAD

**Issue by TimVanOnckelen** [TimVanOnckelen/nbbproject-backend-ap#25]
@winderickxeli , de post voor het aanmaken van een gebruiker lijkt niet te werken. Ik heb nog niet verder doorgetest in de backend, maar zowel in de frontend als in de swagger krijg ik een 500 error.

**Comment by winderickxeli** [comment]
Funky!
![image](https://github.com/TimVanOnckelen/nbbproject-backend-ap/assets/42890887/77ad328c-3c8d-4f28-9cdc-d2b68be25da3)

**Comment by winderickxeli** [comment]
Issue gevonden!
![image](https://github.com/TimVanOnckelen/nbbproject-backend-ap/assets/42890887/fb8e51ce-f543-4478-9740-df18b2a2aa48)

Op het einde van de POST action probeerde ik de gebruiker op te halen met de Id maar die Get method heeft username nodig.
``return CreatedAtAction(nameof(Get), new {newUser.UserName}, newUser);``

**Comment by winderickxeli** [comment]
Ik ben de nieuwe versie aan het publishen. Is zo meteen online!
